name: Container
on: [push]

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: pipenv
    - name: Install pipenv
      run: pip install pipenv
    - name: Install dependencies, check that lockfile is synced
      run: pipenv install --dev --deploy
      
  docker_publish:
    name: Publish built docker container
    runs-on: "ubuntu-latest"
    needs:
      - install
    if: success() && (github.ref_name == 'main' || github.ref_name == 'master')
    steps:
      - uses: actions/checkout@v3

      # https://github.com/marketplace/actions/push-to-ghcr
      - name: Build and publish a Docker image
        uses: macbre/push-to-ghcr@v12
        with:
          image_name: uwcs/progcomp-web
          github_token: ${{ secrets.GITHUB_TOKEN }}